vpcs:


  - name: "main-vpc"
    cidr: "10.0.0.0/16"

    max_azs: 2
    subnets:
      - name: "public"
        type: "PUBLIC"
        cidr_mask: 24
      - name: "private"
        type: "PRIVATE_WITH_EGRESS"
        cidr_mask: 24
eks:
  - name: "basic-eks-cluster"
    vpc: "main-vpc"
    admin_roles:
      - arn: "arn:aws:iam::533267104533:user/testuser"
    # node_groups:
    #   - name: "default-node-group"
    #     min_size: 1
    #     max_size: 3
    #     desired_size: 2
    manifests:
        - name: "namespace"      # Manifest name 
          file: "manifest/namespace.yaml"
        - name: "neginx"       
          file: "manifest/deployment.yaml"
        - name: "nginx-service"    
          file: "manifest/service1.yaml"
         - name: "dep2"      # Manifest name 
          file: "manifest/deployment1.yaml"
        - name: "se2"       
          file: "manifest/service.yaml"
        - name: "nginx-ingress"    
          file: "manifest/ingress.yaml"
    

       

        #deployed by lambda layer at deploy time  define  eks resource  
    


    # helm_charts:
    
 
