apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-1
  namespace: demo-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app-1
  template:
    metadata:
      labels:
        app: demo-app-1
    spec:
      containers:
      - name: demo-app-1
        image: nginx:latest
        ports:
        - containerPort: 80
